// Code generaTed by fileb0x at "2019-07-04 12:13:14.02064 +0800 CST m=+0.104980333" from config file "b0x.yaml" DO NOT EDIT.
// modified(2019-07-04 12:08:17.068455976 +0800 CST)
// original path: swagger-ui/dist/index.html

package swaggerFiles

import (
	_ "embed"
	"os"
)

// FileIndexHTML is "/index.html"
//go:embed index.html
var FileIndexHTML []byte

func init() {

	f, err := FS.OpenFile(CTX, "/index.html", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileIndexHTML)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
