// Code generaTed by fileb0x at "2019-07-04 12:13:14.481375 +0800 CST m=+0.565716624" from config file "b0x.yaml" DO NOT EDIT.
// modified(2019-07-04 12:08:17.067960163 +0800 CST)
// original path: swagger-ui/dist/favicon-16x16.png

package swaggerFiles

import (
	_ "embed"
	"os"
)

// FileFavicon16x16Png is "/favicon-16x16.png"
//go:embed favicon-16x16.png
var FileFavicon16x16Png []byte

func init() {

	f, err := FS.OpenFile(CTX, "/favicon-16x16.png", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileFavicon16x16Png)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
