// Code generaTed by fileb0x at "2019-07-04 12:13:14.034042 +0800 CST m=+0.118382228" from config file "b0x.yaml" DO NOT EDIT.
// modified(2019-07-04 12:08:17.07778456 +0800 CST)
// original path: swagger-ui/dist/swagger-ui-bundle.js

package swaggerFiles

import (
	_ "embed"
	"os"
)

// FileSwaggerUIBundleJs is "/swagger-ui-bundle.js"
//go:embed swagger-ui-bundle.js
var FileSwaggerUIBundleJs []byte

func init() {

	f, err := FS.OpenFile(CTX, "/swagger-ui-bundle.js", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileSwaggerUIBundleJs)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
