// Code generaTed by fileb0x at "2019-07-04 12:13:14.740673 +0800 CST m=+0.825015659" from config file "b0x.yaml" DO NOT EDIT.
// modified(2019-07-04 12:08:17.131302308 +0800 CST)
// original path: swagger-ui/dist/swagger-ui.css.map

package swaggerFiles

import (
	_ "embed"
	"os"
)

// FileSwaggerUICSSMap is "/swagger-ui.css.map"
//go:embed swagger-ui.css.map
var FileSwaggerUICSSMap []byte

func init() {

	f, err := FS.OpenFile(CTX, "/swagger-ui.css.map", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileSwaggerUICSSMap)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
