// Code generaTed by fileb0x at "2019-07-04 12:13:14.482496 +0800 CST m=+0.566837477" from config file "b0x.yaml" DO NOT EDIT.
// modified(2019-07-04 12:08:17.135844661 +0800 CST)
// original path: swagger-ui/dist/swagger-ui.js

package swaggerFiles

import (
	_ "embed"
	"os"
)

// FileSwaggerUIJs is "/swagger-ui.js"
//go:embed swagger-ui.js
var FileSwaggerUIJs []byte

func init() {

	f, err := FS.OpenFile(CTX, "/swagger-ui.js", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileSwaggerUIJs)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
