// Code generaTed by fileb0x at "2019-07-04 12:13:14.480493 +0800 CST m=+0.564834763" from config file "b0x.yaml" DO NOT EDIT.
// modified(2019-07-04 12:08:17.068173899 +0800 CST)
// original path: swagger-ui/dist/favicon-32x32.png

package swaggerFiles

import (
	_ "embed"
	"os"
)

// FileFavicon32x32Png is "/favicon-32x32.png"
//go:embed favicon-32x32.png
var FileFavicon32x32Png []byte

func init() {

	f, err := FS.OpenFile(CTX, "/favicon-32x32.png", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileFavicon32x32Png)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
