// Code generaTed by fileb0x at "2019-07-04 12:13:14.021791 +0800 CST m=+0.106131300" from config file "b0x.yaml" DO NOT EDIT.
// modified(2019-07-04 12:08:17.131106709 +0800 CST)
// original path: swagger-ui/dist/swagger-ui.css

package swaggerFiles

import (
	_ "embed"
	"os"
)

// FileSwaggerUICSS is "/swagger-ui.css"
//go:embed swagger-ui.css
var FileSwaggerUICSS []byte

func init() {

	f, err := FS.OpenFile(CTX, "/swagger-ui.css", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileSwaggerUICSS)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
