---
name: CI
permissions:
  contents: write
  packages: write
  statuses: write
  issues: read
  checks: write
  pull-requests: write
  id-token: write

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  ci:
    uses: "Traive-Finance/workflow-template/.github/workflows/golang-pkg-ci.yml@main"
    secrets: inherit
